before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: jS0pD9QbJpUUkH+vxf9MJo7dm59smKz4EoxMOWlhYStJFrkl5788oPLJe5pOKjWv5cFxTzcXYerar8YhubQGGE83kQkN3B/rbc4rvh1Yvd9Jh9O7r4smwt6IdmX1nk60ViGFy5pajn1m1cA5e1gH2NX1zJp2ATNkBB/dlEbIm2aBlAt/UA7VFYuKvGezXbDuUDsIlB1Awv04NFmbx0JvaHowkGMc7zt5gy3p0CgQ0ZAxwYNitzR5S3nyweeUPDlaGzNsBPA2bZBOYm/kDN7lZC8NYeUOPaGNZVVDzzbRUiridD1f5kI8oNuQkNfSLnQVTjCRjR0nujBH/nT2sTI3xn9F5LRbmRLt05WfO+VTc7X4cHo62/4E5f4UWpuKSeJKOKu/8PJd5yOHPhMybau/bhnVqxQBndMHVa2KUa8CVeDCcTazDJOQ2iEt4ncCyph1v82/UpbR8pDHAJfZwNibN5RT2sdhk2db9ujZriULcZuxJVkx4m25HPFzXFfJBCqMxmuUKKnEknjfWkgpaMwAVcvOUQaCiKRoAPr2SKM2zuLhtOGhIUPbkUqfm+tRqnurPmHbZkv/8jltARWrJIUTTljYqAK7uCfWgAEoyx81dxuqCAXcyWHY/qEiVWhsoLybU8oxyVe7NyU4V6Vq42zQfqLcx1qBtEj/eDMoe0TP5yI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
